[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000

[window]
decorations = "none"
startup_mode = "Maximized"
