tap "thoughtbot/formulae"
tap "vitorgalvao/tiny-scripts"
tap "homebrew/cask-fonts"

brew "openssl"
brew "readline"
brew "bash"
brew "bash-completion"
brew "coreutils"
brew "pkg-config"
brew "fzf"
brew "git"
brew "gnupg"
brew "gpg-agent"
brew "lsd"
brew "neovim"
brew "pinentry-mac"
brew "ripgrep"
brew "tmux", args: ["build-from-source"]
brew "thoughtbot/formulae/rcm"
brew "vitorgalvao/tiny-scripts/cask-repair"

cask "font-hack-nerd-font"
cask "hammerspoon"
cask "iterm2"
cask "keybase"
cask "xscreensaver"
