tap "vitorgalvao/tiny-scripts"
tap "homebrew/cask-fonts"

brew "openssl"
brew "readline"
brew "bash"
brew "bash-completion"
brew "coreutils"
brew "pkg-config"
brew "fzf"
brew "git"
brew "gnupg"
brew "jrnl"
brew "lsd"
brew "neovim"
brew "pinentry-mac"
brew "chruby"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "rcm"
brew "vitorgalvao/tiny-scripts/cask-repair"

cask "font-hack-nerd-font"
cask "hammerspoon"
cask "keybase"
cask "xscreensaver"
cask "alacritty"
